version: '3.8'

services:
  bot:
    build: .
    environment:
      - DISCORD_TOKEN=your_token
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/remindme
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=remindme
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
