FROM ubuntu:latest
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates libssl-dev && rm -rf /var/lib/apt/lists/*
COPY remindme_bot /app/remindme_bot
RUN chmod +x remindme_bot
ENV DISCORD_TOKEN=YOUR_DISCORD_TOKEN
CMD ["/app/remindme_bot"]
